site_name: SCALE documentation
docs_dir: docs/
extra_css:
  - style.css
site_url: https://docs.scale-lang.com
theme:
  name: material
  custom_dir: overrides
  logo: logo_white.svg
  favicon: favicon.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.footer
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - content.code.copy
    - toc.follow

extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/spectral-compute
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/spectral-compute
  - icon: fontawesome/brands/discord
    link: https://discord.gg/KNpgGbTc38

copyright: Copyright &copy; 2024 <a href="https://www.spectralcompute.co.uk">Spectral Compute Ltd</a>

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Navigation and file naming conventions:
#
# - Please refrain from setting custom titles for pages.
#   Instead, modify the top-level title in the corresponding file.
# - Please try to name files in a predictable way - their names will become links.
# - Don't rely on numbered filename prefixes -- we don't need to override their ordering,
#   as we don't use the autogenerated `nav`.

nav:
  - README.md
  - manual/CHANGELOG.md
  - Getting Started:
    - manual/how-to-install.md
    - manual/how-to-use.md
    - manual/comparison.md
    - Examples:
      - examples/README.md
      - examples/basic.md
      - examples/ptx.md
      - examples/blas.md
  - Diving deeper:
    - manual/troubleshooting.md
    - manual/compute-capabilities.md
    - manual/dialects.md
    - manual/differences.md
    - manual/runtime-extensions.md
    - manual/how-to-install-unstable.md
    - Compiler:
      - manual/inline-ptx.md
      - manual/diagnostic-flags.md
      - manual/language-extensions.md
    - Implemented APIs:
      - manual/apis.md
      - manual/api-driver.md
      - manual/api-math.md
      - manual/api-runtime.md
  - Contact Us:
    - contact/report-a-bug.md
  - Legal:
    - licensing.md
    - notices.md
